# Logistic regression

In [106]:
import pandas as pd 
import seaborn as sns

from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score, precision_score

In [107]:
heart_df = pd.read_csv("heart.csv")
# heart_df.info()   
# heart_df["target"].nunique()
heart_df.head()

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [108]:
X = heart_df.drop(columns=["target"])
y = heart_df["target"]

X.head()

   age  sex  cp  trestbps  chol  fbs  ...  thalach  exang  oldpeak  slope  ca  thal
0   63    1   3       145   233    1  ...      150      0      2.3      0   0     1
1   37    1   2       130   250    0  ...      187      0      3.5      0   0     2
2   41    0   1       130   204    0  ...      172      0      1.4      2   0     2
3   56    1   1       120   236    0  ...      178      0      0.8      2   0     2
4   57    0   0       120   354    0  ...      163      1      0.6      2   0     2

[5 rows x 13 columns]

In [109]:
# Test train split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)



#check equal split for binary classfication - 50/50 for both class

# y_train[y_train == 1]             #122
# y_train[y_train == 0]             #109

## Part 1 : Apply logistic regression

In [110]:
model = LogisticRegression(max_iter=10000)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("accuracy score : ", accuracy*100, "%")

precision = precision_score(y_test, y_pred)
print("Precision score : ", precision*100, "%")

accuracy score :  88.52459016393442 %
Precision score :  87.87878787878788 %

## Part 2 : Scaling 
### Standardisation -> then applying Logistic regression

In [111]:
# scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.fit(X_test)

X_train

array([[-1.35679832,  0.72250438,  0.00809909, ...,  0.95390513,
        -0.68970073, -0.50904773],
       [ 0.38508599,  0.72250438, -0.97189094, ...,  0.95390513,
        -0.68970073,  1.17848036],
       [-0.92132724,  0.72250438,  0.98808912, ..., -0.69498803,
        -0.68970073, -0.50904773],
       ...,
       [ 1.58263146,  0.72250438,  1.96807914, ..., -0.69498803,
         0.32186034, -0.50904773],
       [-0.92132724,  0.72250438, -0.97189094, ...,  0.95390513,
        -0.68970073,  1.17848036],
       [ 0.92942484, -1.38407465,  0.00809909, ...,  0.95390513,
         1.33342142, -0.50904773]], shape=(242, 13))

In [120]:
## confusion matrix

from sklearn.metrics import confusion_matrix , classification_report ,  accuracy_score , precision_score, recall_score , f1_score

cm = confusion_matrix(y_test, y_pred)

print(cm , "\n")

print(classification_report(y_test, y_pred))


print("accuracy score : ", accuracy_score(y_test, y_pred))
print("precision score : ", precision_score(y_test, y_pred))
print("recall score : ", recall_score(y_test, y_pred))
print("f1 score : ", f1_score(y_test, y_pred))

[[25  4]
 [ 3 29]]

              precision    recall  f1-score   support

           0       0.89      0.86      0.88        29
           1       0.88      0.91      0.89        32

    accuracy                           0.89        61
   macro avg       0.89      0.88      0.88        61
weighted avg       0.89      0.89      0.89        61

accuracy score :  0.8852459016393442
precision score :  0.8787878787878788
recall score :  0.90625
f1 score :  0.8923076923076924